FROM golang:latest AS builder

WORKDIR /app
COPY ../go.mod ../go.sum ./
RUN go mod download

COPY . .
COPY ./create-article-service/main.go . 

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root

#COPY --from=builder /app/main .
COPY --from=builder /app ./

CMD ["./main"]
