// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID      int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Author  *string    `gorm:"column:author" json:"author"`
	Title   *string    `gorm:"column:title" json:"title"`
	Body    *string    `gorm:"column:body" json:"body"`
	Created *time.Time `gorm:"column:created" json:"created"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
